"""Shared command default values."""

DEFAULT_RETRIEVAL_K = 5
DEFAULT_MIN_SCORE = 0.5
DEFAULT_EXPAND = 5
DEFAULT_FULL_DOC_THRESHOLD = 0
DEFAULT_VERBOSE = True


DEFAULT_D = 5
DEFAULT_MIN_SCORE_FOR_DOCUMENTS = 0.50

DEFAULT_D_FOR_IFRS_DOCUMENTS = 3
DEFAULT_D_FOR_IAS_DOCUMENTS = 3
DEFAULT_D_FOR_IFRIC_DOCUMENTS = 5
DEFAULT_D_FOR_SIC_DOCUMENTS = 5
DEFAULT_D_FOR_PS_DOCUMENTS = 1

DEFAULT_MIN_SCORE_FOR_IFRS_DOCUMENTS = 0.59
DEFAULT_MIN_SCORE_FOR_IAS_DOCUMENTS = 0.55
DEFAULT_MIN_SCORE_FOR_IFRIC_DOCUMENTS = 0.51
DEFAULT_MIN_SCORE_FOR_SIC_DOCUMENTS = 0.51
DEFAULT_MIN_SCORE_FOR_PS_DOCUMENTS = DEFAULT_MIN_SCORE_FOR_DOCUMENTS


def get_default_document_d_by_type() -> dict[str, int]:
    """Return the default per-document-type document caps."""
    return {
        "IFRS": DEFAULT_D_FOR_IFRS_DOCUMENTS,
        "IAS": DEFAULT_D_FOR_IAS_DOCUMENTS,
        "IFRIC": DEFAULT_D_FOR_IFRIC_DOCUMENTS,
        "SIC": DEFAULT_D_FOR_SIC_DOCUMENTS,
        "PS": DEFAULT_D_FOR_PS_DOCUMENTS,
    }


def get_default_document_min_score_by_type() -> dict[str, float]:
    """Return the default per-document-type document score thresholds."""
    return {
        "IFRS": DEFAULT_MIN_SCORE_FOR_IFRS_DOCUMENTS,
        "IAS": DEFAULT_MIN_SCORE_FOR_IAS_DOCUMENTS,
        "IFRIC": DEFAULT_MIN_SCORE_FOR_IFRIC_DOCUMENTS,
        "SIC": DEFAULT_MIN_SCORE_FOR_SIC_DOCUMENTS,
        "PS": DEFAULT_MIN_SCORE_FOR_PS_DOCUMENTS,
    }
