"""Shared command default values."""

DEFAULT_RETRIEVAL_K = 5
DEFAULT_MIN_SCORE = 0.55
DEFAULT_EXPAND = 5
DEFAULT_FULL_DOC_THRESHOLD = 0
DEFAULT_VERBOSE = True


DEFAULT_D = 5
DEFAULT_MIN_SCORE_FOR_DOCUMENTS = 0.50
