"""Build the Promptfoo configuration from family-owned source files."""

from __future__ import annotations

import argparse
import logging
import os
import re
import sys
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Literal, TypeAlias, cast

import yaml

logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.retrieval.retrieval_contract import build_promptfoo_retrieve_assertions, parse_retrieve_contract

PromptfooSuite: TypeAlias = Literal["answer", "retrieve"]
BASE_CONFIG_PATHS: dict[PromptfooSuite, Path] = {
    "answer": PROJECT_ROOT / "promptfoo_src" / "base.answer.yaml",
    "retrieve": PROJECT_ROOT / "promptfoo_src" / "base.retrieve.yaml",
}
QUESTIONS_ROOT = PROJECT_ROOT / "experiments" / "00_QUESTIONS"
PROMPTFOO_CONFIG_DIR_ENV = "PROMPTFOO_CONFIG_DIR"
GENERATED_HEADER = [
    "# This file is generated by scripts/build_promptfoo_config.py.",
    "# Do not edit it by hand. Update promptfoo_src/base.answer.yaml,",
    "# promptfoo_src/base.retrieve.yaml, and the relevant family.yaml files,",
    "# then rerun one of:",
    "#   uv run python scripts/build_promptfoo_config.py --suite answer",
    "#   uv run python scripts/build_promptfoo_config.py --suite retrieve",
    "",
]


def get_default_output_path() -> Path:
    """Determine the default output path from PROMPTFOO_CONFIG_DIR.

    Raises:
        EnvironmentError: If PROMPTFOO_CONFIG_DIR is not set.
    """
    config_dir_env = os.environ.get(PROMPTFOO_CONFIG_DIR_ENV)
    if not config_dir_env:
        raise EnvironmentError(f"{PROMPTFOO_CONFIG_DIR_ENV} environment variable is not set. This script must be run with PROMPTFOO_CONFIG_DIR pointing to a directory.")
    config_dir = Path(config_dir_env)
    if config_dir.is_absolute():
        return config_dir / "promptfooconfig.yaml"
    return PROJECT_ROOT / config_dir / "promptfooconfig.yaml"


YamlScalar: TypeAlias = str | int | float | bool | None
YamlValue: TypeAlias = YamlScalar | dict[str, "YamlValue"] | list["YamlValue"]
YamlObject: TypeAlias = dict[str, YamlValue]


@dataclass(frozen=True)
class PromptfooBaseConfig:
    """Static top-level Promptfoo configuration."""

    evaluate_options: YamlObject
    prompts: list[YamlValue]
    providers: list[YamlValue]
    readme: str


@dataclass(frozen=True)
class PromptfooVariant:
    """One phrasing variant within a question family."""

    variant_id: str
    file_name: str
    description: str


@dataclass(frozen=True)
class PromptfooFamily:
    """A family-owned set of assertions and question variants."""

    family_id: str
    assertion_key: str
    options: YamlObject | None
    assertions: list[YamlValue]
    variants: list[PromptfooVariant]
    family_dir: Path

    @property
    def assertion_anchor(self) -> str:
        """Return the YAML anchor name for this family assertions block."""
        normalized_family = re.sub(r"[^a-z0-9]+", "_", self.family_id.lower()).strip("_")
        return f"{normalized_family}_assertions"


class PromptfooConfigBuilder:
    """Build the checked-in Promptfoo configuration file."""

    def __init__(self, project_root: Path, suite: PromptfooSuite = "answer") -> None:
        """Initialize the builder for one repository root."""
        self._project_root = project_root
        self._suite = suite
        self._base_config_path = BASE_CONFIG_PATHS[suite]
        self._questions_root = project_root / "experiments" / "00_QUESTIONS"
        self._output_path: Path | None = None

    def build_text(self, output_path: Path) -> str:
        """Build the full Promptfoo YAML text."""
        self._output_path = output_path
        base_config = self._load_base_config()
        families = self._load_families()
        logger.info(f"Building Promptfoo config for suite={self._suite} from {len(families)} family file(s)")

        lines: list[str] = [*GENERATED_HEADER]
        lines.extend(self._render_mapping_entry("evaluateOptions", base_config.evaluate_options, indent=0))
        lines.append("")
        lines.extend(self._render_mapping_entry("prompts", base_config.prompts, indent=0))
        lines.append("")
        providers = self._rewrite_exec_commands(base_config.providers)
        lines.extend(self._render_mapping_entry("providers", providers, indent=0))
        lines.append("")
        if families:
            lines.append("tests:")
            lines.extend(self._render_tests(families))
        else:
            lines.append("tests: []")

        lines.append("")
        lines.extend(self._render_mapping_entry("readme", base_config.readme, indent=0))
        lines.append("")
        return "\n".join(lines)

    def write_output(self, output_path: Path) -> None:
        """Write the generated Promptfoo config to disk."""
        output_text = self.build_text(output_path)
        output_path.write_text(output_text, encoding="utf-8")
        logger.info(f"Wrote generated Promptfoo config to {output_path}")

    def _load_base_config(self) -> PromptfooBaseConfig:
        """Load the static Promptfoo base config."""
        raw_base_config = self._load_yaml_document(self._base_config_path)
        base_mapping = self._require_mapping(raw_base_config, context=f"{self._base_config_path}")

        evaluate_options = self._require_yaml_object(base_mapping.get("evaluateOptions"), context="evaluateOptions")
        prompts = self._require_yaml_list(base_mapping.get("prompts"), context="prompts")
        providers = self._require_yaml_list(base_mapping.get("providers"), context="providers")
        readme = self._require_string(base_mapping.get("readme"), context="readme")

        return PromptfooBaseConfig(
            evaluate_options=evaluate_options,
            prompts=prompts,
            providers=providers,
            readme=readme,
        )

    def _load_families(self) -> list[PromptfooFamily]:
        """Load all family definitions under experiments/00_QUESTIONS."""
        family_paths = sorted(self._questions_root.glob("*/family.yaml"))
        families: list[PromptfooFamily] = []
        for family_path in family_paths:
            family = self._load_family(family_path)
            if family is None:
                continue
            families.append(family)
        return families

    def _load_family(self, family_path: Path) -> PromptfooFamily | None:
        """Load one family definition."""
        raw_family_config = self._load_yaml_document(family_path)
        family_mapping = self._require_mapping(raw_family_config, context=f"{family_path}")

        family_id = self._require_string(family_mapping.get("family_id"), context=f"{family_path}: family_id")
        assertion_key = "assert" if self._suite == "answer" else "assert_retrieve"
        options = self._load_family_options(family_mapping, family_path=family_path)
        raw_assertions = family_mapping.get(assertion_key)
        if raw_assertions is None:
            logger.info(f"Skipping family {family_id} for suite={self._suite}; missing {assertion_key}")
            return None
        if self._suite == "retrieve" and isinstance(raw_assertions, Mapping):
            contract = parse_retrieve_contract(raw_assertions, context=f"{family_path}: {assertion_key}")
            assertions = build_promptfoo_retrieve_assertions(contract)
        else:
            assertions = self._require_yaml_list(raw_assertions, context=f"{family_path}: {assertion_key}")
        variants = self._load_variants(family_mapping.get("variants"), family_path=family_path)

        family = PromptfooFamily(
            family_id=family_id,
            assertion_key=assertion_key,
            options=options,
            assertions=self._rewrite_file_uris(assertions),
            variants=variants,
            family_dir=family_path.parent,
        )
        self._validate_family_files(family)
        return family

    def _load_family_options(self, family_mapping: Mapping[str, object], family_path: Path) -> YamlObject | None:
        """Load optional family-level Promptfoo test options."""
        raw_defaults = family_mapping.get("defaults")
        if raw_defaults is None:
            return None

        defaults = self._require_yaml_object(raw_defaults, context=f"{family_path}: defaults")
        raw_options = defaults.get("options")
        if raw_options is None:
            return None

        return self._require_yaml_object(raw_options, context=f"{family_path}: defaults.options")

    def _load_variants(self, raw_variants: object, family_path: Path) -> list[PromptfooVariant]:
        """Load variants from one family document."""
        variants_sequence = self._require_sequence(raw_variants, context=f"{family_path}: variants")
        variants: list[PromptfooVariant] = []

        for index, raw_variant in enumerate(variants_sequence):
            variant_mapping = self._require_mapping(raw_variant, context=f"{family_path}: variants[{index}]")
            variant_id = self._require_string(variant_mapping.get("id"), context=f"{family_path}: variants[{index}].id")
            file_name = self._require_string(variant_mapping.get("file"), context=f"{family_path}: variants[{index}].file")
            description = self._require_string(variant_mapping.get("description"), context=f"{family_path}: variants[{index}].description")
            variants.append(PromptfooVariant(variant_id=variant_id, file_name=file_name, description=description))

        if not variants:
            message = f"{family_path}: expected at least one variant"
            raise ValueError(message)

        return variants

    def _validate_family_files(self, family: PromptfooFamily) -> None:
        """Validate that declared variant files exist."""
        for variant in family.variants:
            question_path = family.family_dir / variant.file_name
            if not question_path.exists():
                message = f"Missing question file for {variant.variant_id}: {question_path}"
                raise FileNotFoundError(message)

    def _load_yaml_document(self, path: Path) -> object:
        """Load one YAML document from disk."""
        logger.info(f"Loading YAML document from {path}")
        raw_document = yaml.safe_load(path.read_text(encoding="utf-8"))
        return cast("object", raw_document)

    def _render_tests(self, families: Sequence[PromptfooFamily]) -> list[str]:
        """Render the Promptfoo tests list."""
        lines: list[str] = []

        for family_index, family in enumerate(families):
            if family_index > 0:
                lines.append("")

            for variant_index, variant in enumerate(family.variants):
                if lines and lines[-1] != "":
                    lines.append("")
                lines.extend(self._render_test_case(family=family, variant=variant, variant_index=variant_index))

        return lines

    def _render_test_case(self, family: PromptfooFamily, variant: PromptfooVariant, variant_index: int) -> list[str]:
        """Render one Promptfoo test case."""
        if self._output_path is None:
            raise RuntimeError("_output_path must be set before calling _render_test_case")

        question_path = family.family_dir / variant.file_name
        project_relative = question_path.relative_to(self._project_root)
        relative_question_path = Path(os.path.relpath(question_path, start=self._output_path.parent)).as_posix()
        metadata: YamlObject = {
            "family": f"{family.family_id}¤",
            "variant": f"{variant.variant_id}¤",
            "question_path": project_relative.as_posix(),
        }
        description = f"{variant.variant_id} - {variant.description}"

        lines = self._render_mapping_entry("vars", {"question": f"file://{relative_question_path}"}, indent=2, is_list_item=True)
        if family.options is not None:
            lines.extend(self._render_mapping_entry("options", family.options, indent=4))
        lines.extend(self._render_mapping_entry("metadata", metadata, indent=4))
        lines.extend(self._render_mapping_entry("description", description, indent=4))

        rendered_assertion_key = "assert"
        if variant_index == 0:
            lines.append(f"    {rendered_assertion_key}: &{family.assertion_anchor}")
            lines.extend(self._render_list_items(family.assertions, indent=6))
        else:
            lines.append(f"    {rendered_assertion_key}: *{family.assertion_anchor}")

        return lines

    def _rewrite_file_uris(self, value: YamlValue) -> YamlValue:
        """Rewrite relative file:// URIs so they resolve from the generated config directory."""
        if self._output_path is None:
            raise RuntimeError("_output_path must be set before rewriting file URIs")

        if isinstance(value, dict):
            return {key: self._rewrite_file_uris(item) for key, item in value.items()}
        if isinstance(value, list):
            return [self._rewrite_file_uris(item) for item in value]
        if not isinstance(value, str) or not value.startswith("file://"):
            return value

        raw_path = value.removeprefix("file://")
        candidate_path = Path(raw_path)
        if candidate_path.is_absolute():
            return value

        normalized_raw_path = raw_path.removeprefix("./")
        absolute_target_path = self._project_root / normalized_raw_path
        relative_target_path = Path(os.path.relpath(absolute_target_path, start=self._output_path.parent)).as_posix()
        return f"file://{relative_target_path}"

    def _rewrite_exec_commands(self, value: YamlValue) -> YamlValue:
        """Rewrite provider exec commands so script paths are anchored to the repository root."""
        if isinstance(value, dict):
            return {key: self._rewrite_exec_commands(item) for key, item in value.items()}
        if isinstance(value, list):
            return [self._rewrite_exec_commands(item) for item in value]
        if not isinstance(value, str):
            return value

        match = re.fullmatch(r"exec:uv run python (?P<script_path>\S+)(?P<suffix>.*)", value)
        if match is None:
            return value

        script_path = Path(match.group("script_path"))
        if script_path.is_absolute():
            return value

        script_name = script_path.name
        absolute_script_path = (self._project_root / "scripts" / script_name).resolve()
        suffix = match.group("suffix")
        return f"exec:uv run python {absolute_script_path.as_posix()}{suffix}"

    def _render_mapping(self, mapping: YamlObject, indent: int) -> list[str]:
        """Render a YAML mapping."""
        lines: list[str] = []
        for key, value in mapping.items():
            lines.extend(self._render_mapping_entry(key, value, indent=indent))
        return lines

    def _render_mapping_entry(self, key: str, value: YamlValue, indent: int, *, is_list_item: bool = False) -> list[str]:
        """Render one YAML mapping entry."""
        entry_prefix = " " * indent
        child_indent = indent + 4 if is_list_item else indent + 2
        if is_list_item:
            entry_prefix += "- "
        key_prefix = f"{entry_prefix}{key}:"

        if isinstance(value, dict):
            if not value:
                return [f"{key_prefix} {{}}"]
            return [key_prefix, *self._render_mapping(value, indent=child_indent)]

        if isinstance(value, list):
            if not value:
                return [f"{key_prefix} []"]
            return [key_prefix, *self._render_list_items(value, indent=child_indent)]

        if isinstance(value, str) and "\n" in value:
            block_lines = [f"{key_prefix} |"]
            block_lines.extend(self._render_block_string(value, indent=child_indent))
            return block_lines

        return [f"{key_prefix} {self._render_scalar(value)}"]

    def _render_list_items(self, values: Sequence[YamlValue], indent: int) -> list[str]:
        """Render YAML list items."""
        lines: list[str] = []
        for value in values:
            lines.extend(self._render_list_item(value, indent=indent))
        return lines

    def _render_list_item(self, value: YamlValue, indent: int) -> list[str]:
        """Render one YAML list item."""
        item_prefix = " " * indent + "-"

        if isinstance(value, dict):
            if not value:
                return [f"{item_prefix} {{}}"]
            mapping_lines = self._render_mapping(value, indent=indent + 2)
            first_mapping_line = mapping_lines[0].lstrip()
            return [f"{item_prefix} {first_mapping_line}", *mapping_lines[1:]]

        if isinstance(value, list):
            if not value:
                return [f"{item_prefix} []"]
            nested_lines = self._render_list_items(value, indent=indent + 2)
            first_nested_line = nested_lines[0].lstrip()
            return [f"{item_prefix} {first_nested_line}", *nested_lines[1:]]

        if isinstance(value, str) and "\n" in value:
            return [f"{item_prefix} |", *self._render_block_string(value, indent=indent + 2)]

        return [f"{item_prefix} {self._render_scalar(value)}"]

    def _render_block_string(self, value: str, indent: int) -> list[str]:
        """Render a YAML block scalar body."""
        return [f"{' ' * indent}{line}" for line in value.splitlines()]

    def _render_scalar(self, value: YamlScalar) -> str:
        """Render one scalar YAML value."""
        if value is None:
            return "null"
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, int | float):
            return str(value)
        escaped_value = value.replace("'", "''")
        return f"'{escaped_value}'"

    def _require_mapping(self, value: object, context: str) -> Mapping[str, object]:
        """Require a mapping with string keys."""
        if not isinstance(value, Mapping):
            message = f"{context}: expected a mapping"
            raise TypeError(message)
        for key in value:
            if not isinstance(key, str):
                message = f"{context}: expected string keys"
                raise TypeError(message)
        return cast("Mapping[str, object]", value)

    def _require_sequence(self, value: object, context: str) -> Sequence[object]:
        """Require a sequence that is not a string."""
        if isinstance(value, str | bytes | bytearray) or not isinstance(value, Sequence):
            message = f"{context}: expected a sequence"
            raise TypeError(message)
        return cast("Sequence[object]", value)

    def _require_string(self, value: object, context: str) -> str:
        """Require a string value."""
        if not isinstance(value, str):
            message = f"{context}: expected a string"
            raise TypeError(message)
        return value

    def _require_yaml_object(self, value: object, context: str) -> YamlObject:
        """Require a YAML object value."""
        mapping = self._require_mapping(value, context=context)
        return {key: self._to_yaml_value(item, context=f"{context}.{key}") for key, item in mapping.items()}

    def _require_yaml_list(self, value: object, context: str) -> list[YamlValue]:
        """Require a YAML list value."""
        sequence = self._require_sequence(value, context=context)
        return [self._to_yaml_value(item, context=f"{context}[{index}]") for index, item in enumerate(sequence)]

    def _to_yaml_value(self, value: object, context: str) -> YamlValue:
        """Convert a parsed YAML node to the supported typed representation."""
        if value is None or isinstance(value, str | int | float | bool):
            return value

        if isinstance(value, Mapping):
            yaml_object: YamlObject = {}
            for key, item in value.items():
                if not isinstance(key, str):
                    message = f"{context}: expected string keys"
                    raise TypeError(message)
                yaml_object[key] = self._to_yaml_value(item, context=f"{context}.{key}")
            return yaml_object

        if isinstance(value, Sequence) and not isinstance(value, str | bytes | bytearray):
            return [self._to_yaml_value(item, context=f"{context}[]") for item in value]

        message = f"{context}: unsupported YAML value type: {type(value)!r}"
        raise ValueError(message)


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments for the Promptfoo config builder."""
    parser = argparse.ArgumentParser(description="Build promptfooconfig.yaml from question-family source files")
    parser.add_argument(
        "--suite",
        choices=("answer", "retrieve"),
        default="answer",
        help="Promptfoo suite to build (answer uses promptfoo_src/base.answer.yaml; retrieve uses promptfoo_src/base.retrieve.yaml)",
    )
    parser.add_argument(
        "--project-root",
        type=Path,
        default=PROJECT_ROOT,
        help="Path to the repository root containing promptfoo_src/ and experiments/00_QUESTIONS/",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=f"Path to write the generated promptfooconfig.yaml file. Defaults to $PROMPTFOO_CONFIG_DIR/promptfooconfig.yaml if set, otherwise {PROJECT_ROOT / 'promptfooconfig.yaml'}",
    )
    return parser.parse_args()


def main() -> int:
    """Run the Promptfoo config builder."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    args = parse_args()

    # Resolve output path: explicit arg takes precedence, otherwise require env var
    if args.output is not None:
        output_path = args.output
    else:
        try:
            output_path = get_default_output_path()
        except EnvironmentError:
            logger.error(f"{PROMPTFOO_CONFIG_DIR_ENV} is not set and --output was not provided")
            return 1

    logger.info(f"Writing promptfooconfig.yaml to: {output_path}")

    builder = PromptfooConfigBuilder(project_root=args.project_root, suite=args.suite)
    builder.write_output(output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
